### ISSUE TITLE
Unable to Use `fromFile` as Described in README.md

### ISSUE THREAD

**Issue by hasan-ozbey** [Borewit/strtok3#1195]
I am trying to use `fromFile` as described in the README.md, but I can't get it to work.

According to the README:
```ts
import * as strtok3 from 'strtok3';

const tokenizer = await strtok3.fromFile(file);
```
This results in:
```console
TypeError: strtok3.fromFile is not a function
```
I also tried:
```ts
import { fromFile } from 'strtok3';

const tokenizer = await fromFile(file);
```
But this gives:
```console
The requested module '.../node_modules/.cache/vite/client/deps/strtok3.js...' doesn't provide an export named 'fromFile'
```
I’m not sure if I’m missing something or if this is an issue with the library itself.

---
Additionally, could you confirm if `fromFile` is the recommended approach for handling input files?
```ts
const files = (event.target as HTMLInputElement).files
const file = files[0]
```

**Comment by Borewit** [comment]
I will try to give you some guidance how to get **strtok3** working in an Electron application, especially in combination with an Electron + Vite setup, follow these steps to integrate it properly:

### 1. Use strtok3.fromFile in the Main Process
In Electron, file operations like `strtok3.fromFile` should be performed in the main process. Reasons:
- The **strtok3** library requires Node.js-specific capabilities to handle files, which are only available in the main process.
- File I/O operations should be avoided in the render process to prevent blocking the UI and degrading the user experience.

### 2. Ensure ESM Compatibility
If your project uses ECMAScript Modules (ESM), ensure that your Electron and Vite configurations support ESM. For older 
setups using CommonJS, make the necessary adjustments in your Electron configuration. For loading an ESM module in TypeScript, which is very tricky, I recommend to use: [load-esm](https://github.com/Borewit/load-esm). 

 ### 3. Set Up IPC Communication
Since the render process in Electron operates within Chromium, it cannot directly access Node.js APIs like strtok3. Use 
Electron's IPC (Inter-Process Communication) mechanism to pass data between the main and render processes.

_I have **not tested** the code below, it is just illustrative to my advice._

#### Main Process: Parse the File
Use [strtok3.fromFile](https://github.com/Borewit/strtok3?tab=readme-ov-file#fromfile-function) in the main process to parse files and best to expose the results to the render process via IPC. 

```js
// main.js
import { app, ipcMain } from 'electron';
import { fromFile } from 'strtok3';
import path from 'path';

ipcMain.handle('parse-file', async (event, filePath) => {
  try {
    const tokenizer = await fromFile(filePath);
    // Example: Read the first 100 bytes of the file
    const buffer = Buffer.alloc(100);
    await tokenizer.readBuffer(buffer, { length: 100 });
    await tokenizer.close();

    return { filePath, buffer: buffer.toString('hex') }; // Return metadata or data as needed
  } catch (error) {
    console.error('Error parsing file:', error);
    throw error; // Pass the error back to the renderer for handling
  }
});

app.whenReady().then(() => {
  // Your app initialization logic here
});
```

#### Render Process: Request Data
In the render process, use ipcRenderer to request and receive data from the main process.

```js
// renderer.js
import { ipcRenderer } from 'electron';

async function parseFile(filePath) {
  try {
    const result = await ipcRenderer.invoke('parse-file', filePath);
    console.log('Parsed Result:', result);
    return result;
  } catch (error) {
    console.error('Error parsing file:', error);
    return null; // Handle or display the error as appropriate
  }
}

// Example usage
const filePath = '/path/to/your/file.bin';
parseFile(filePath).then(result => {
  if (result) {
    console.log('Parsed File Data:', result);
  }
});
```
This approach ensures efficient use of strtok3 by handling file parsing in the main process and passing the results to the render process. It maintains a responsive UI and adheres to Electron's architecture. 

Please let me know what did and did not work for you.

**Comment by hasan-ozbey** [comment]
wow! Thanks for the detailed answer.
