### ISSUE TITLE
Distributed files refer to `exports`, which isn't available in browsers

### ISSUE THREAD

**Issue by DanielHeath** [Borewit/strtok3#128]
EG: `core.js` in the latest version on npm starts with: `Object.defineProperty(exports, "__esModule", { value: true });`.

This doesn't work in browsers or webpack. 

[this post](https://blog.rendall.dev/posts/2019/1/14/problem-typescript-adds-objectdefinepropertyexports-esmodule-value-true/) suggests it's caused by `tsconfig.json` having `"module": "commonjs"` (because commonjs is not supported in browsers).

I think this is caused by

**Comment by Borewit** [comment]
common.js seems to be the choice for Node.js.

For browser usage, the code is post-processed, there I see no big issue using `commonjs`. Webpack does support `commonjs` and should be able to process this module.

This issue is related to yours: https://github.com/Microsoft/TypeScript/issues/15685

[Here is a list of web projects](https://github.com/Borewit/music-metadata-browser/network/dependents) using strtok3 via [music-metadata-browser](https://github.com/Borewit/music-metadata-browser).
