### ISSUE TITLE
Why is BufferTokenizer.peekBuffer() async?

### ISSUE THREAD

**Issue by beenotung** [Borewit/strtok3#551]
From the source code it appears to be only performing sync operations:
https://github.com/Borewit/strtok3/blob/22c7b180c0df73c8567b9fc692320b091c7029c0/lib/BufferTokenizer.ts#L43-L54

**Comment by Borewit** [comment]
The reason it is async, is for interface compatibility with other (async) tokenisers.

**Comment by Borewit** [comment]
The underlying transport mechanism should be transparent. Depending on the transport / stream type it may take some time when data is retrieved. That is the reason why it is async. There is no way converting async to sync. I don't the overhead is big issue, only when _byte hunting_, in my experience, it has noticeable overhead.

**Comment by beenotung** [comment]
I noticed this library when I try to figure out why `FileType.fromBuffer(buffer)` is async. That library read the first few bytes of a buffer, to detect the mime type of the content. The bytes are already loaded so async is not needed but it's using an async method from strtok3...

https://www.npmjs.com/package/file-type

**Comment by Borewit** [comment]
file-type used to be sync, until the point we could not detect certain file types within the first 4100 bytes. Now we read in in a stream kind of fashion, and as far as required to determine the file type. Since we made it async, like many other operations which potentially are time consuming operations.

**Comment by beenotung** [comment]
@Borewit do you mean file-type handle the data beyond first 4100 bytes in stream fashion not because of the cost to read from file but for the cost on processing data. Hence it is async even when detecting the file type from Buffer (not file) ?

**Comment by Borewit** [comment]
It is async to be complaint with streams, reading from files or other means we fetch the data. That data **may** not be instantly there, that is why it is async.

Because the internal logic needs to work independent from the underlying storage / transport, everything is async. The fact that you provide a Buffer, does not change that need abstract functionality requires to be called async.

In the past this module only read from a buffer, and no further then the 4100 which had all kind of limitations.

**Comment by beenotung** [comment]
If the internal function are written in callback manner, then it can work with data source from both Buffer and Stream 🤔

**Comment by Borewit** [comment]
> If the internal function are written in callback manner, then it can work with data source from both Buffer and Stream

That's it. And even other ways to access files. For example [music-metadata](https://github.com/Borewit/music-metadata) can be used in combination with [tokenizer-s3](https://github.com/Borewit/tokenizer-s3) to read metadata from a file which is stored in the Amazon S3 cloud, by only reading those parts of the file holding the metadata ([code](https://github.com/Borewit/tokenizer-s3#reading-audio-metadata-from-amazon-s3)). 

Also possible to determine just the file type directly on the cloud ([code](https://github.com/sindresorhus/file-type#filetypefromtokenizertokenizer)). 

It is [this library](https://github.com/Borewit/strtok3) which makes that possible as kind of middle-ware.

You may, but I can read a buffer of 4100 and then I determine the file type based on that buffer. What if that is enough data to determine the file type? The difference is, that this allows mechanism allows you to read what is required. But reading typically cost time, and things which cost are async (callbacks, is kind of the same thing).
